# Generated by Django 4.1.7 on 2023-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GC_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('timeline', models.DateTimeField()),
                ('genre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hostel_score', models.IntegerField()),
                ('event', models.ManyToManyField(to='scoreboard.gc')),
            ],
        ),
    ]
