# Generated by Django 4.1.7 on 2023-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
