# Generated by Django 4.1.7 on 2023-06-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_hostel_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='total_score',
        ),
    ]
