# Generated by Django 4.1.7 on 2023-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_remove_hostel_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
