# Generated by Django 4.1.7 on 2023-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_hostel_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
