# Generated by Django 4.1.7 on 2023-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_hostel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='number',
            field=models.IntegerField(),
        ),
    ]
